runtime: nodejs12

handlers:
  - url: /
    static_files: my-nodejs-service/views/index.html
    upload: my-nodejs-service/views/index.html

  - url: /(.)
    static_files: build/\1
    upload: build/(.)
